/**
 * Metadata for the one logical Nigeria.
 * The current bounded simulation is a prototype, not full national game state.
 */
export const worldDescriptor = Object.freeze({
  id: "nigeria-main",
  name: "Nigeria",
  projectName: "Naija: One World",
  topology: "single-logical-world",
  implementationStage: 21,
  simulationImplemented: true,
  simulationScope: "bounded-multiplayer-prototype",
  geographyImplemented: true,
  geographyScope: "national-admin-registry-plus-bounded-akure-south-sample",
  educationImplemented: true,
  educationScope: "fictional-configurable-education-prototype",
  lifeSimulationImplemented: true,
  lifeSimulationScope: "configurable-calendar-family-relationships-and-life-history-foundation",
  careersImplemented: true,
  careersScope: "server-authoritative-configurable-vacancies-employment-work-sessions-and-payroll-prototype",
  economyImplemented: true,
  economyScope: "naira-denominated-ledger-banking-market-goods-tax-estimation-and-credit-prototype",
  businessesImplemented: true,
  businessesScope: "configurable-business-templates-products-inventory-sales-production-expenses-and-ownership-prototype",
  housingImplemented: true,
  housingScope: "configurable-property-types-ownership-listings-rental-agreements-sales-maintenance-and-furnishing-prototype",
  governmentImplemented: true,
  governmentScope: "federal-state-local-government-structure-offices-appointments-budgets-projects-and-announcements-prototype",
  electionsImplemented: true,
  electionsScope: "political-parties-elections-candidates-campaigns-voting-results-and-government-office-integration-prototype",
  justiceImplemented: true,
  justiceScope: "laws-courts-cases-evidence-hearings-judgments-fines-appeals-and-legislative-proposals-prototype",
  policeImplemented: true,
  policeScope: "stations-officers-recruitment-incidents-dispatch-investigations-evidence-wanted-records-arrests-misconduct-and-audits-prototype",
  militaryImplemented: true,
  militaryScope: "organizations-bases-units-recruitment-training-ranks-promotions-command-appointments-assignments-leave-assets-national-security-events-discipline-and-audits-prototype",
  crimeImplemented: true,
  crimeScope: "crime-definitions-incidents-resolution-detection-evidence-criminal-records-notoriety-restitution-rehabilitation-and-integration-with-police-justice-economy-prototype",
  cultureImplemented: true,
  cultureScope: "communities-institutions-religious-traditional-memberships-cultural-profiles-festivals-events-projects-announcements-disputes-reputation-and-geography-integration-prototype",
  entertainmentImplemented: true,
  socialImplemented: true,
  entertainmentScope: "professions-creator-profiles-music-projects-film-productions-content-creation-events-contracts-journalism-fame-monetization-and-moderation-prototype",
  transportationImplemented: true,
  transportationScope: "road-network-vehicle-ownership-purchase-fuel-maintenance-public-transport-routes-trips-cargo-shipments-driver-licenses-facilities-and-routing-prototype",
  npcImplemented: true,
  npcScope: "npc-profiles-routines-needs-goals-activities-simulation-engine-population-generation-decision-logging-and-world-event-reactions-prototype",
  worldEventsImplemented: true,
  worldEventsScope: "world-event-framework-causal-chains-event-consumers-geographic-scope-idempotency-and-multi-system-integration-prototype",
  geographicCoverage: "national-admin-registry-plus-bounded-akure-south-sample",
  fullNationalGeography: false,
  fullNationalSimulation: false,
} as const);
